# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 275ef41e5b7d080030dc7d82a5b4b3f6db5d529da1eebdd2cf9817cd09782d61bfe92a9c849bef9927070fd51d33f31ea4e28469026055e5e2e5a478e61ed4f0

test:
  secret_key_base: f22026e4b0d81b090a2e0715b01aa3132d8053237bccf30d19a4023e4acf504d7c39fbfdfac1bed2494a68ef2213719df1b01f6e829e891ea2588e1390098242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
